#!/bin/bash

cd ~/Yandex.Disk/Eclipse/LINUX/simple-fb2-reader/gui

touch ../Debug/gui/simple-fb2-reader.glade.o

objcopy	--input binary \
	--output elf64-x86-64 \
	--binary-architecture i386 \
	simple-fb2-reader.glade ../Debug/gui/simple-fb2-reader.glade.o
